language: java

install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
